public with sharing class PS_SalesforceTokenWrapper {
    public String access_token;	//00D5h000008MocX!ARIAQKsaQ2z4CGukrJSzXWwGbeOwEPaWitJ4h5b1K0TnmG9Axm1SAIQQu16.LHJRo3sfiPi_KbAwcf9D.RgiGU.HTINGFuQ5
	public String signature;	//+EJ3fc6OCkyQtkgC9DRDncY/nfChO8DTSC5DKGqyGCU=
	public String scope;	//cdp_query_api web cdp_segment_api api full
	public String id_token;	
	public String instance_url;	//https://gepower-a-dev-ed.develop.my.salesforce.com
	public String id;	//https://login.salesforce.com/id/00D5h000008MocXEAS/0055h000009QyU1AAK
	public String token_type;	//Bearer
	public String issued_at;	//1769664364880
	public String refresh_token;
}